{{- if .Values.apiServer.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bureau.fullname" . }}-api-server
  labels:
    {{- include "bureau.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  minAvailable: {{ .Values.apiServer.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "bureau.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-server
{{- end }}
---
{{- if .Values.workers.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bureau.fullname" . }}-workers
  labels:
    {{- include "bureau.labels" . | nindent 4 }}
    app.kubernetes.io/component: workers
spec:
  minAvailable: {{ .Values.workers.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "bureau.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: workers
{{- end }}
