#!/usr/bin/env node
/**
 * Bureau — dev JWT keypair bootstrap.
 *
 * Generates an RS256 keypair and writes it to .env (gitignored) so
 * `docker compose up` can pass it through to api-server, which
 * requires JWT_PRIVATE_KEY_PEM + JWT_PUBLIC_KEY_PEM in production mode
 * (see server-env.ts).
 *
 * This is for LOCAL DEV and CI only — never use these keys anywhere
 * real. The keys are written ONLY to a local .env file and are
 * deterministic per-run by accident of timing.
 *
 * Idempotent: skips if .env already contains both PEMs.
 */
import { generateKeyPairSync } from "node:crypto";
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = resolve(__dirname, "..", ".env");

const PEM_HEADER_PRIVATE = "-----BEGIN PRIVATE KEY-----";
const PEM_HEADER_PUBLIC = "-----BEGIN PUBLIC KEY-----";

function hasBothPemKeys(contents) {
  return (
    contents.includes(PEM_HEADER_PRIVATE) &&
    contents.includes(PEM_HEADER_PUBLIC) &&
    contents.includes("JWT_PRIVATE_KEY_PEM=") &&
    contents.includes("JWT_PUBLIC_KEY_PEM=")
  );
}

function loadOrGenerate() {
  if (existsSync(ENV_PATH)) {
    const existing = readFileSync(ENV_PATH, "utf-8");
    if (hasBothPemKeys(existing)) {
      console.log("✅ .env already contains JWT keys — skipping generation");
      return;
    }
  }

  console.log("🔑 Generating fresh RS256 keypair for dev JWT…");
  const { privateKey, publicKey } = generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });

  // 32-byte hex = 64 chars (test conventions)
  const encryptionKey = "0".repeat(64);
  const superKey = `bureau_dev_super_${Date.now().toString(36)}`;

  const block = [
    "",
    "# Auto-generated by scripts/gen-dev-jwt.mjs — DO NOT COMMIT",
    `JWT_PRIVATE_KEY_PEM="${privateKey.replace(/\n/g, "\\n")}"`,
    `JWT_PUBLIC_KEY_PEM="${publicKey.replace(/\n/g, "\\n")}"`,
    `API_KEY_ENCRYPTION_KEY="${encryptionKey}"`,
    `BUREAU_SUPER_KEY="${superKey}"`,
    "",
  ].join("\n");

  let base = "";
  if (existsSync(ENV_PATH)) {
    const existing = readFileSync(ENV_PATH, "utf-8");
    // strip any prior auto-generated block
    base = existing.replace(
      /\n*# Auto-generated by scripts\/gen-dev-jwt\.mjs[\s\S]*?(?=\n# |\n$|$)/g,
      "",
    );
    // ensure trailing newline
    if (!base.endsWith("\n")) base += "\n";
  }

  writeFileSync(ENV_PATH, base + block, "utf-8");
  console.log(`✅ Wrote JWT keys + dev secrets to ${ENV_PATH}`);
}

loadOrGenerate();